# SPDX-FileCopyrightText: 2025 Imran M <imran@imranmustafa.net>
# SPDX-License-Identifier: GPL-3.0-or-later
* Brainf*ck Interpreter/Compiler
The [[https://brainfuck.org/][Brainf*ck]] programming language is very weird and impractical for
production use. None of this stopped me from writing a
interpreter/compiler for it. Which you can use for all your
+nonexistent+ Brainf*ck needs.

You are welcome.
* Usage
** Interpreter Mode 
To use interpreter mode pass the files to the program with no
arguments.
#+begin_src sh
bfic [FILE]...
#+end_src
*** REPL
If you don't pass any arguments, the program will start a REPL. Which
allows you to interactively run Brainf*uck code.
#+begin_src sh
bfic
#+end_src
** Compiler Mode 
You can also turn Brainf*ck code to a binary by passing ~-c~ before
the files you want to compile.
#+begin_src sh
bfic -c [FILE]...
#+end_src
* Building
This project uses cargo and nix so either ~cargo build -r~ or ~nix build~ will work.
* Copyright/Licensing
Copyright (C) 2024-2025 Imran M <imran@imranmustafa.net>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or (at
your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
